#!/usr/bin/env node
/**
 * Regenerates the marker-delimited sections of README.md from the real game
 * data: the inventory tables and the badge catalog table.
 *
 * It imports src/data/*.ts directly rather than parsing the source, so the
 * tables are whatever the game actually ships — they can't drift from the data
 * the way hand-written ones do.
 *
 * Requires Node 23.6+ (or 22.6+ run with --experimental-strip-types), where
 * TypeScript type annotations are stripped natively. Note the deploy workflow
 * pins Node 22, so don't wire `--check` into CI without bumping that first.
 *
 * Usage:
 *   npm run stats              rewrite the generated sections
 *   npm run stats -- --check   exit 1 if they're out of date (no writes)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const README = fileURLToPath(new URL('../README.md', import.meta.url));

const { masterInventory } = await import('../src/data/inventory.ts');
const { BADGES } = await import('../src/data/badges.ts');
const { CARD_COUNTS } = await import('../src/data/constants.ts');

const THEME_LABELS = { city: 'City', highway: 'Highway', country: 'Country', general: 'General' };
const CATEGORY_LABELS = { vehicle: 'Vehicle', object: 'Object', creature: 'Creature' };
const BADGE_GROUPS = ['Score', 'Bonuses', 'Trips', 'Spotting'];

const hasBonus = (i) => i.bonus !== null;
const total = masterInventory.length;
const withBonus = masterInventory.filter(hasBonus).length;
const maxDeck = Math.max(...CARD_COUNTS);

// ---------- Inventory tables ----------

/** One row per group, in the given key order, with a totals row. */
function countTable(heading, keys, labels, keyOf) {
  const rows = keys.map((key) => {
    const items = masterInventory.filter((i) => keyOf(i) === key);
    const b = items.filter(hasBonus).length;
    return `| ${labels[key] ?? key} | ${items.length} | ${b} | ${items.length - b} |`;
  });
  return [
    `| ${heading} | Items | With bonus | Plain |`,
    '| --- | ---: | ---: | ---: |',
    ...rows,
    `| **Total** | **${total}** | **${withBonus}** | **${total - withBonus}** |`
  ].join('\n');
}

const themes = Object.keys(THEME_LABELS);
const categories = Object.keys(CATEGORY_LABELS);
const points = [...new Set(masterInventory.map((i) => i.points))].sort((a, b) => a - b);

// A themed trip deals from its own theme plus the shared 'general' pool.
const generalCount = masterInventory.filter((i) => i.theme === 'general').length;
const playable = themes
  .filter((t) => t !== 'general')
  .map((t) => `${THEME_LABELS[t]} ${masterInventory.filter((i) => i.theme === t).length + generalCount}`)
  .join(', ');

const inventorySection = `**${total} items** in total: **${withBonus}** carry a bonus challenge, **${total - withBonus}** are plain one-tap spots.

#### By theme

${countTable('Theme', themes, THEME_LABELS, (i) => i.theme)}

\`general\` items are mixed into every themed trip, so a themed drive deals from more than
its own row above: ${playable}. "Surprise Me" ignores theme entirely and deals from all
${total} items, up to ${maxDeck} cards.

#### By point value

${countTable('Points', points, Object.fromEntries(points.map((p) => [p, `${p} pts`])), (i) => i.points)}

#### By category

${countTable('Category', categories, CATEGORY_LABELS, (i) => i.category)}`;

// ---------- Badge table ----------

/** The highest multiplier a rule can be satisfied with, read off the options. */
const badgeRows = BADGES.map((b) => `| ${b.group} | **${b.name}** | ${b.description} |`);

const badgeSection = `All **${BADGES.length}** badges, in catalog order — the profile screen shows this same list,
with locked ones greyed out as goals to chase.

| Group | Badge | How to earn |
| --- | --- | --- |
${BADGE_GROUPS.flatMap((g) => badgeRows.filter((r) => r.startsWith(`| ${g} |`))).join('\n')}

**Score**, **Bonuses** and **Spotting** badges unlock the moment you qualify, mid-trip,
with a toast and a celebration. **Trips** badges can only become true once a trip is
recorded, so they land on the end-of-trip summary.`;

// ---------- Write ----------

const readme = readFileSync(README, 'utf8');

// Git checks this file out with CRLF on Windows. Emitting LF regardless would
// make --check report "stale" on every fresh clone and leave mixed endings
// behind, so match whatever the file already uses.
const eol = readme.includes('\r\n') ? '\r\n' : '\n';

function replaceSection(text, name, body) {
  const start = `<!-- ${name}:start -->`;
  const end = `<!-- ${name}:end -->`;
  const a = text.indexOf(start);
  const b = text.indexOf(end);
  if (a === -1 || b === -1) {
    console.error(`Could not find the ${start} / ${end} markers in README.md.`);
    process.exit(1);
  }
  const block = [start, `<!-- Generated by \`npm run stats\` — do not edit by hand. -->`, '', body, end]
    .join('\n')
    .replace(/\n/g, eol);
  return text.slice(0, a) + block + text.slice(b + end.length);
}

let updated = replaceSection(readme, 'inventory-stats', inventorySection);
updated = replaceSection(updated, 'badge-table', badgeSection);

if (process.argv.includes('--check')) {
  if (updated !== readme) {
    console.error('README generated sections are out of date. Run `npm run stats`.');
    process.exit(1);
  }
  console.log('README generated sections are up to date.');
} else {
  writeFileSync(README, updated);
  console.log(
    `Updated README.md — ${total} items (${withBonus} with a bonus, ${total - withBonus} plain), ${BADGES.length} badges.`
  );
}
