#!/usr/bin/env node
/**
 * Regenerates the "Inventory at a glance" section of README.md from the real
 * inventory data.
 *
 * It imports src/data/inventory.ts directly rather than parsing the source, so
 * the numbers are whatever the game actually ships — they can't drift from the
 * data the way hand-written counts do.
 *
 * Requires Node 23.6+ (or 22.6+ run with --experimental-strip-types), where
 * TypeScript type annotations are stripped natively. Note the deploy workflow
 * pins Node 22, so don't wire `--check` into CI without bumping that first.
 *
 * Usage:
 *   npm run stats          update README.md between the marker comments
 *   npm run stats -- --check   exit 1 if the README is out of date (no writes)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const README = fileURLToPath(new URL('../README.md', import.meta.url));
const START = '<!-- inventory-stats:start -->';
const END = '<!-- inventory-stats:end -->';

const { masterInventory } = await import('../src/data/inventory.ts');
const { CARD_COUNTS } = await import('../src/data/constants.ts');

const THEME_LABELS = { city: 'City', highway: 'Highway', country: 'Country', general: 'General' };
const CATEGORY_LABELS = { vehicle: 'Vehicle', object: 'Object', creature: 'Creature' };

const hasBonus = (i) => i.bonus !== null;
const total = masterInventory.length;
const withBonus = masterInventory.filter(hasBonus).length;

/** One table row per group, in the given key order, with a totals row. */
function table(heading, keys, labels, keyOf) {
  const rows = keys.map((key) => {
    const items = masterInventory.filter((i) => keyOf(i) === key);
    const b = items.filter(hasBonus).length;
    return `| ${labels[key] ?? key} | ${items.length} | ${b} | ${items.length - b} |`;
  });
  return [
    `| ${heading} | Items | With bonus | Plain |`,
    '| --- | ---: | ---: | ---: |',
    ...rows,
    `| **Total** | **${total}** | **${withBonus}** | **${total - withBonus}** |`
  ].join('\n');
}

const themes = Object.keys(THEME_LABELS);
const categories = Object.keys(CATEGORY_LABELS);
const points = [...new Set(masterInventory.map((i) => i.points))].sort((a, b) => a - b);

// A themed trip deals from its own theme plus the shared 'general' pool.
const generalCount = masterInventory.filter((i) => i.theme === 'general').length;
const playable = themes
  .filter((t) => t !== 'general')
  .map((t) => {
    const own = masterInventory.filter((i) => i.theme === t).length;
    return `${THEME_LABELS[t]} ${own + generalCount}`;
  })
  .join(', ');

const section = `${START}
<!-- Generated by \`npm run stats\` — do not edit by hand. -->

**${total} items** in total: **${withBonus}** carry a bonus challenge, **${total - withBonus}** are plain one-tap spots.

#### By theme

${table('Theme', themes, THEME_LABELS, (i) => i.theme)}

\`general\` items are mixed into every themed trip, so a themed drive deals from
more than its own row above: ${playable}. "Surprise Me" ignores theme entirely
and deals from all ${total}, up to ${Math.max(...CARD_COUNTS)} cards.

#### By point value

${table('Points', points, Object.fromEntries(points.map((p) => [p, `${p} pts`])), (i) => i.points)}

#### By category

${table('Category', categories, CATEGORY_LABELS, (i) => i.category)}
${END}`;

const readme = readFileSync(README, 'utf8');
const startIdx = readme.indexOf(START);
const endIdx = readme.indexOf(END);
if (startIdx === -1 || endIdx === -1) {
  console.error(`Could not find the ${START} / ${END} markers in README.md.`);
  process.exit(1);
}

// Git checks this file out with CRLF on Windows. Emitting LF regardless would
// make --check report "stale" on every fresh clone and leave mixed endings
// behind, so match whatever the file already uses.
const eol = readme.includes('\r\n') ? '\r\n' : '\n';
const body = eol === '\n' ? section : section.replace(/\n/g, eol);

const updated = readme.slice(0, startIdx) + body + readme.slice(endIdx + END.length);

if (process.argv.includes('--check')) {
  if (updated !== readme) {
    console.error('README inventory stats are out of date. Run `npm run stats`.');
    process.exit(1);
  }
  console.log('README inventory stats are up to date.');
} else {
  writeFileSync(README, updated);
  console.log(`Updated README.md — ${total} items, ${withBonus} with a bonus, ${total - withBonus} plain.`);
}
